### ISSUE TITLE
backward compatibility with @ctypedef and @cstruct

### ISSUE THREAD

**Issue by hros** [analytech-solutions/CBinding.jl#108]
I have code that uses an older version of CBinding and implements the C structs using
```julia
@ctypedef julia_typename @cstruct name {
    field1::Cuint
    filed2::Cuint[4]
    field3::Culonglong
}
```

how would that be implemented in the current version of CBinding?

**Comment by krrutkow** [comment]
You can use the C type definition directly now, something like this (assuming you already have a compiler context ``` c`` ```):
```julia
c"""
  typedef struct name {
    unsigned int field1;
    unsigned int field2[4];
    unsigned long long field3;
  } julia_typename;
"""j
```

**Comment by hros** [comment]
thanks!
what is the preferred/standard "compiler context"?

**Comment by krrutkow** [comment]
For something like just defining types, you can use ``` c`` ```.  But if you wish to create bindings to libraries and such you will need to specify header/library file paths, libraries to link to, etc., like you would use on the command line for GCC or Clang: ``` c`-I/path/to/headers -L/path/to/libs -lmylib` ```
