### ISSUE TITLE
size_t type

### ISSUE THREAD

**Issue by hros** [analytech-solutions/CBinding.jl#113]
I am including a C header file, which in turns includes `stddef.h` in order to use `size_t`
When parsing the file with `CBinding` I am getting an error that `size_t` is unknown

Following the example code, I added:
```julia
const c"size_t"   = UInt64
```
But I'd prefer `size_t` to be machine dependent
1. are `#include` statements in header files parsed by `CBinding`?
if so, why isn't `size_t` recognized?
2. is there another way to declare `size_t` which will use the machine's word size?

**Comment by krrutkow** [comment]
2. Use this instead:
```julia
const c"size_t" = Csize_t
```
1. Yes, but generally you do not want to create bindings for the entire C Standard Library, so if you include the `i` string macro suffix, then only files included that are in the directory (or subdirectory) of the file that you explicitly `#include`-ed.  Here is an example:  https://github.com/analytech-solutions/ExamplesUsingCBinding.jl/blob/2428ebcf85436b09dbd8e75480e94e37370648a1/test/Clang.jl#L14-L19
