### ISSUE TITLE
Add ability to represent C const-ness (i.e. immutable types)

### ISSUE THREAD

**Issue by krrutkow** [analytech-solutions/CBinding.jl#23]
Currently, for simplicity sake, the `const` modifier in C is ignored, but it should be represented with CBinding syntax.

**Comment by krrutkow** [comment]
Using the `time` function from the C library for performance testing:
```jl
julia> module TEST
           mutable struct MutableStruct
               mem::NTuple{sizeof(Clong), UInt8}
           end
           struct ImmutableStruct
               mem::NTuple{sizeof(Clong), UInt8}
           end
           struct Immutable{T, S}
               mem::NTuple{S, UInt8}
               Immutable(mut::T) where {T} = new{T, sizeof(T)}(getfield(mut, :mem))
           end
           mutable struct Mutable{T, S}
               mem::NTuple{S, UInt8}
               Mutable(imm::T) where {T} = new{T, sizeof(T)}(getfield(imm, :mem))
           end
           getMutableStruct() = ccall(:time, MutableStruct, (Ptr{Clong},), C_NULL)
           getImmutableStruct() = ccall(:time, ImmutableStruct, (Ptr{Clong},), C_NULL)
           getImmutable() = Immutable(getMutableStruct())
           getMutable() = Mutable(getImmutableStruct())
       end

julia> @benchmark TEST.getMutableStruct()
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     10.589 ns (0.00% GC)
  median time:      11.212 ns (0.00% GC)
  mean time:        21.617 ns (37.88% GC)
  maximum time:     60.240 μs (99.97% GC)
  --------------
  samples:          10000
  evals/sample:     999

julia> @benchmark TEST.getImmutableStruct()
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     6.442 ns (0.00% GC)
  median time:      6.449 ns (0.00% GC)
  mean time:        6.482 ns (0.00% GC)
  maximum time:     18.044 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> @benchmark TEST.getMutable()
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     15.629 ns (0.00% GC)
  median time:      16.115 ns (0.00% GC)
  mean time:        26.602 ns (31.22% GC)
  maximum time:     60.564 μs (99.95% GC)
  --------------
  samples:          10000
  evals/sample:     998

julia> @benchmark TEST.getImmutable()
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     6.428 ns (0.00% GC)
  median time:      6.434 ns (0.00% GC)
  mean time:        6.535 ns (0.00% GC)
  maximum time:     19.141 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```

So it looks like Julia will optimize out the need of a memory allocation for the mutable temporary when it is wrapped with `Immutable()`.  This could allow users to work with immutable (non-allocating) forms of the C aggregate types (which are defined as mutable by default) simply by wrapping with `Immutable()` (or perhaps `Const()` instead).  They would then behave similarly to a C `const` object.

Alternatively, CBinding could default to always declaring immutable structs and users can wrap with `Mutable()` to create mutable forms of them.  While this approach seems more Julian and is less reliant on compiler optimizations for performance, it also results in less a C-like syntax and is a more intrusive change to make.

@cdsousa Would either of these approaches help resolve the trade-off you mentioned [here](https://github.com/JuliaGPU/CUDAdrv.jl/issues/165#issuecomment-547349954)?

**Comment by cdsousa** [comment]
Well, I didn't actually work on the CUDAdrv.jl wrap and I don't have that much experience wrapping C libs. I don't have any preference. Maybe others can better contribute to the discussion, like @maleadt or others currently using Clang.jl.

It may happens that one of these solutions scales better than the other, and that will decide the choice.

**Comment by krrutkow** [comment]
Added with #24
