### ISSUE TITLE
UndefVarError: Cbool not defined

### ISSUE THREAD

**Issue by freemin7** [analytech-solutions/CBinding.jl#49]
I am using the syster package CBindingGen to generate a C binding. During this process CBindingGen emits 𝐣𝐥.Cbool. 
𝐣𝐥.Cbool however is not defined in this package. Any ideas?

**Comment by krrutkow** [comment]
Cbool is now defined, and will be available in the 0.9.3 release.

**Comment by freemin7** [comment]
Thanks!

**Comment by freemin7** [comment]
Do you have any suggestions how to handle it if the wrapper produces names already taken by Julia even in BareModules my wrapper produces a constant called InitError which also conflicts with the one in Core.InitError

**Comment by krrutkow** [comment]
Currently your only option is to return false from the filtering function when that constant is encountered and manually create the binding for it.
