### ISSUE TITLE
Support aggregate construction using NamedTuples to set anonymous aggregate fields

### ISSUE THREAD

**Issue by cdsousa** [analytech-solutions/CBinding.jl#6]
Hi! It would be nice if there was a way to construct a Cstruct by passing all its contents to the constructor, even when it contains anonymous Cstructs or CUnions.

For example, this works:

```julia
julia> @cstruct A {u::@cunion U {x::Cint, y::Cchar}}
A

julia> A(u=U(x=1))
A(u=U(x=1, y=1))
```

But this does not:
```julia
julia> @cstruct B {u::@cunion {x::Cint, y::Cchar}}
B

julia> B(u=(;x=1))
# error
```

**Comment by krrutkow** [comment]
Good find!  Need to allow use of NamedTuples to set anonymous aggregate fields.
```jl
julia> B(u=(x=1,))
```
