### ISSUE TITLE
Using current version of CBinding for reading binary files without @cstruct macro

### ISSUE THREAD

**Issue by wsgreen** [analytech-solutions/CBinding.jl#65]
I have been using CBinding to read a binary file containing c structs as detailed here: [https://www.analytech-solutions.com/analytech-solutions/blog/binary-io.html](https://www.analytech-solutions.com/analytech-solutions/blog/binary-io.html)

However, it seems the @cstruct macro was removed and I am having trouble understanding how to do the same thing in the current version of CBinding

So (very simplified) I used to do something like this:

```
using CBinding

@cstruct data_field {
    Label::UInt8[64];
    Index::Int32;
    Data::Float64;
};

io = open(filename)
while !eof(io)
    data = read(io, data_field)
    # do something with data
end
```

How would I do the equivalent using CBinding v1.0.2?

**Comment by krrutkow** [comment]
You would now create a compiler context, and use the C definition itself, something like this:
```julia
# create compiler context
c``

# use C sized types and define them in Julia (System.jl can provide these bindings for you)
c"#include <stdint.h>"s
const c"uint8_t" = UInt8
const c"int32_t" = Int32

# define the `data_field` type using C sized-types
c"""
struct data_field {
  uint8_t Label[64];
  int32_t Index;
  double Data;
};
"""j

open("/dev/zero") do io
  display(read(io, data_field))
end
# var"(c\"struct data_field\")" (80-byte struct)
#   Label = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
#   Index = 0
#   Data  = 0.0
```
This must be at module scope now as well.

**Comment by krrutkow** [comment]
Depending on your Julia environment, you could also consider placing `CBinding = "^0.9"` in the `[compat]` section of your `Project.toml` file to force the older version of the package (the newer version does does perform significantly faster than the older though).

**Comment by wsgreen** [comment]
Thanks Keith!

I translated my program using your example and I can run it again using version v1.0.2.

The program still crashes while reading an actual file, so obviously I still have some debugging to do :)

BTW, I think it might be helpful to update the example in the blog and include it as an example.

**Comment by wsgreen** [comment]
Closing this issue.
I still have a crashing problem, but I think it is a separate issue, so I will open a new one for that.
