### ISSUE TITLE
Example to "unsafe_wrap" UInt8 Vector to c sturct in new version

### ISSUE THREAD

**Issue by garyfpga** [analytech-solutions/CBinding.jl#70]
Hi,

I wonder if there is an example of how to unsafe_wrap UInt8 Vector to the c struct using the new version?
I had been using @cstruct macro and was able to do so in the old version but I am not very sure how to do that in new version

**Comment by krrutkow** [comment]
Yes, there is [a blog post](https://www.analytech-solutions.com/analytech-solutions/blog/cbinding-v1.html) that has examples of the new usage.  Essentially `unsafe_wrap` is no longer necessary as the new `Cptr` mechanism works transparently.  So given an appropriately typed pointer (such as `Cptr{c"struct S"}`) just dereference the fields as necessary with `ptr.fld[]`.

```julia
c``
c"""
  struct S {
    int i;
    double d;
  };
"""j

arr = zeros(UInt8, sizeof(S))
@info arr
#  [ Info: UInt8[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

ptr = reinterpret(Cptr{S}, pointer(arr))
ptr.i[] = 42
ptr.d[] = 0.1

@info arr
# [ Info: UInt8[0x2a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9a, 0x99, 0x99, 0x99, 0x99, 0x99, 0xb9, 0x3f]
```

**Comment by garyfpga** [comment]
That is so wonderful, thank you for your effort of developing this package

**Comment by garyfpga** [comment]
Hi,

I successfully cast my binary data into Julia variable using the method described here. Everything works fine. But when I try to multithread my pcap decoder with @spawn and run it from jupyter-lab, the kernel crashed without any message.

I wonder if there is some thread-safe issue in the new interface?

Thank you

**Comment by krrutkow** [comment]
That depends on what you are attempting to do:
 - Declaring `c"..."` string macros _is not_ thread-safe.
 - Accessing/manipulating C user-defined types or pointers _is_ thread-safe.
 - Accessing bindings to C global variables or functions _is_ thread-safe.

Without any context, it's hard to be much help, but some other possibilities for what could be causing the crash are:
 - The C user-defined type layout is now determined by libclang, and it seems to be wrong occasionally, depending on version and OS involved, for types using packed alignment strategies, hence:
   - #59 
   - #60
 - Needing to maintain a reference to the Julia object (or use `GC.@preserve`) that your C pointers are referencing data in so the garbage collector doesn't get rid of it on you.
 - CBinding has some unknown bug in it (but we all know that's not possible :wink:).

**Comment by garyfpga** [comment]
Hi Keith,

I used your package in my pcap decoder... So yes I used C bitfields and packed alignment.

I declared c"..." first in the main thread, and then use @spawn to decode multiple pcap files.
Basically I just read in one single UInt8 vector in each of these thread and then cast them to the pointer as you describe. I immediately use those value so the ptr is not used somewhere else.

The pcap decode function works fine if I invoke from the mainthread directly but will crash if it is @spawn-ed and run under IJulia.

and Yes I know it is very unlikely an unknown bug on your side. I think you know what you are doing. Probably you are the guy who researched this kind of stuff in Julia the most.

For now I reverted back to 0.9.0 which I think is quick fast already (I think it is probably ~50% of C++ speed), but you cannot multi-thread it so easily in C++. With Julia, dataframe and GZip package it is hard to beat the Julia version....

I can actually send you my code, if that is not too much. And you can see how people are using your code (well I think you probaly doing the same thing anyway).....

**Comment by krrutkow** [comment]
> I can actually send you my code, if that is not too much.

That would be very helpful, and any other details like Julia version and OS too...  See if I can reproduce the issue figure out if it is a bug in CBinding or not.
