### ISSUE TITLE
Computed field types

### ISSUE THREAD

**Issue by eschnett** [analytech-solutions/CBinding.jl#73]
Your package uses `bitstype(T)` to obtain the "real" type for some types.

In case you are not aware, I want to point to the package [Computed FieldTypes](https://github.com/vtjnash/ComputedFieldTypes.jl) which does a similar thing, but uses a different function name (`fulltype`) for a very similar functionality.

You might want to point to this package in your documentation if you think it's worthwhile, or you could work with @vtjnash to use the same API in both packages.

**Comment by krrutkow** [comment]
In the context of CBinding's usage at least, `bitstype(T)` is semantically much more precise, and `isbitstype(bitstype(T))` is both always true and very intuitive.  Also, the use of `bitstype(T)` is just a temporary artifact of having to work around JuliaLang/julia#269.
