### ISSUE TITLE
Can we generate Julia code?

### ISSUE THREAD

**Issue by Lecrapouille** [analytech-solutions/CBinding.jl#80]
Hi, sorry if I missed the documentation but is this possible to directly generate a Julia file from the C code ? For example:

```
julia> ccode = c"""
typedef struct Foo
{
    double x; double y; int t;
} Foo_t;

void foobar(Foo_t* f) { .... }
"""

julia> transcript(ccode, "foo.jl")
```

Would generate code like

```
# foo.jl
struct Foo
    x::Float64
    y::Float64
    t::Cint
end

function foobar(f::Ptr{Foo})
    ccall((:foobar, thelib), Cvoid, (Ptr{Foo},), f)
end
```

**Comment by krrutkow** [comment]
Yes, the generated code can be saved to a file which can be loaded later, but it is not really the intended or recommended usage of the package.  That is actually what is done for the libclang bindings included with CBinding though.  However, Julia's docstrings and macros do not currently serialize back to code correctly, so the documentation and macro features must be disabled.  The generated code will also not look very Julian, as you can see [here](https://github.com/analytech-solutions/CBinding.jl/blob/master/deps/libclang-12.jl) and has absolute paths to deal with as well.  An example of generating a file can be found [here](https://github.com/krrutkow/P4est.jl/blob/cbinding-v1-pregen/deps/build.jl) where the `generate` function will eventually make its way into CBinding.

What is your reason for wanting to save the bindings to a file?

**Comment by Lecrapouille** [comment]
Thanks, just to help me generating good struct types and ccall (but necessary dynamically), on the same time, someone gave me another way to acheive it:

```
pkg> dev Clang

julia> using Clang.Generators

shell> vim test.h

shell> cat test.h
typedef struct mystruct
{
    double* data;
    int size;
} mystruct_t;

julia> ctx = create_context("test.h")
[ Info: Parsing headers...
Context(...)

julia> build!(ctx)
[ Info: Processing header: test.h
[ Info: Building the DAG...
┌ Warning: default libname: ":libxxx" is being used, did you forget to set `library_name` in the toml file?
└ @ Clang.Generators ~/.julia/dev/Clang/src/generator/audit.jl:16
[ Info: Emit Julia expressions...
struct mystruct
    data::Ptr{Cdouble}
    size::Cint
end

const mystruct_t = mystruct

[ Info: Done!
Context(...)
```
