### ISSUE TITLE
Passing Julia variable by reference

### ISSUE THREAD

**Issue by fleimgruber** [analytech-solutions/CBinding.jl#84]
Given a C function with the signature

```c
DllImport enum DWStatus DWGetNumReaders(int* num_readers);
```

I can do this in Julia Base

```julia
a = 0
status = ccall(Libdl.dlsym(lib, "DWGetNumReaders"), Cint, (Ref{Cint},), a)
```

and tried to do the equivalent with CBinding.jl via (influenced by [these](https://github.com/analytech-solutions/CBinding.jl#using-global-variable-and-function-bindings) docs):

```julia
dwgetnumreaders = c"DWGetNumReaders"
a = 0
dwgetnumreaders(a[])
```

and got this traceback

```
ERROR: LoadError: MethodError: no method matching unsafe_convert(::Type{Cptr{Int32}}, ::Int64)
Closest candidates are:
  unsafe_convert(::Type{Cptr{T}}, ::Ptr) where T at C:\Users\LeimgruberF\.julia\packages\CBinding\0akLv\src\pointers.jl:38
  unsafe_convert(::Type{Cptr{T}}, ::Ref) where T at C:\Users\LeimgruberF\.julia\packages\CBinding\0akLv\src\pointers.jl:39
  unsafe_convert(::Type{Cptr{T}}, ::Array{T,1} where T) where T at C:\Users\LeimgruberF\.julia\packages\CBinding\0akLv\src\pointers.jl:40
  ...
Stacktrace:
 [1] macro expansion at C:\Users\LeimgruberF\.julia\packages\CBinding\0akLv\src\functions.jl:0 [inlined]
 [2] funccall(::Type{var"(c\"enum DWStatus\")"}, ::Type{Tuple{Cptr{Int32}}}, ::Val{:cdecl}, ::Cbinding_DWGetNumReaders{:DWGetNumReaders}, ::Int64) at C:\Users\LeimgruberF\.julia\packages\CBinding\0akLv\src\functions.jl:32
```

so I guess I am missing the correct way of doing the `Ref{Cint}` ("pointer to int") equivalent for the Julia variable `a`. Am I on the right track or is there another approach needed or recommended in CBinding.jl?

**Comment by krrutkow** [comment]
I believe you are wanting something like this?
```julia
a = Ref{Cint}(0)
dwgetnumreaders(a)
```

**Comment by fleimgruber** [comment]
Thanks, that works, although I thought I could have `a` with a plain Julia `Int64` type as with the `ccall` example. I guess I will somehow have to do this conversion myself afterwards?

Also, a related quick follow-up, given this C header:

```c
struct DWFileInfo
{
...
};

DllImport enum DWStatus DWOpenDataFile(char* file_name, struct DWFileInfo* file_info);
```

and then (ideally having `fileinfo` as a plain Julia struct afterwards):

```julia
dwopendatafile = c"DWOpenDataFile"

FileInfo = c"struct DWFileInfo"
fileinfo = Cptr{FileInfo}()
println(fileinfo)

dwfilepath = "test/testfiles/Example_Drive01.d7d"
status = dwopendatafile(dwfilepath, fileinfo)
println(status)
```

prints

```
Cptr{var"c\"struct DWFileInfo\""}(0x0000000000000000)
c"DWSTAT_ERROR_NO_MEMORY_ALLOC"
```

so it seems that `fileinfo` is not declared quite right, as I am getting a DLL error returned related to memory allocation for the target `fileinfo`? I am just wrapping my head around most of this for the first time, so sorry for the naive questions. I guess I could in turn at least help to put this in the docs under a section that deals with these kinds of C APIs?

**Comment by fleimgruber** [comment]
After reading the docs more carefully, I came up with
```julia
dwopendatafile = c"DWOpenDataFile"

FileInfo = c"struct DWFileInfo"
fileinfo = Libc.malloc(FileInfo())

dwfilepath = "test/testfiles/Example_Drive01.d7d"
status = dwopendatafile(dwfilepath, fileinfo)
println(status)
println(fileinfo)
println(fileinfo[])
```
which prints:
```
c"DWSTAT_OK"
Cptr{var"(c\"struct DWFileInfo\")"}(0x000000002102b7a0)
var"(c\"struct DWFileInfo\")"(sample_rate=100.0, start_store_time=37903.8942918056, duration=95.8)
```
So that part at least works now.

Still, I am thinking about a good way of exposing the C API results as plain Julia types - ideally with the help of CBinding.jl if possible.

**Comment by krrutkow** [comment]
Yes, depending on the C API, there are several options for obtaining the block of memory (and pointer referencing it).  It could come from an existing C data structure, C global variable, a `Ref`, an explicit memory allocation, etc.  Usually, if a Julia-allocated object's fields must be written from Julia throughout the lifetime of the object, then using `Libc.malloc` (and `Libc.free`) is necessary.  If instead the fields are only set when the object is allocated, then using a `Ref` might be more convenient.

**Comment by krrutkow** [comment]
Also, if you use the `j` string macro suffix (like `c"..."j`) when you create your bindings, then the Julia-friendly names will be generated so you wouldn't need to declare `FileInfo = c"struct DWFileInfo"`.

**Comment by fleimgruber** [comment]
> Also, if you use the j string macro suffix (like c"..."j) when you create your bindings, then the Julia-friendly names will be generated so you wouldn't need to declare FileInfo = c"struct DWFileInfo".

Thanks, a very helpful suffix indeed!

**Comment by fleimgruber** [comment]
> Yes, depending on the C API, there are several options for obtaining the block of memory (and pointer referencing it). It could come from an existing C data structure, C global variable, a Ref, an explicit memory allocation, etc. Usually, if a Julia-allocated object's fields must be written from Julia throughout the lifetime of the object, then using Libc.malloc (and Libc.free) is necessary. If instead the fields are only set when the object is allocated, then using a Ref might be more convenient.

Yes, in the use-case I was concerned with, the `Ref` was the proper fit. Also, for the case `c"struct Type *"` I was wondering what the best solution would be. I read through the source and really liked https://github.com/analytech-solutions/CBinding.jl/blob/aa367c60f915a262638bb138f55e71442c9df432/src/pointers.jl#L6 together with https://github.com/analytech-solutions/CBinding.jl/blob/aa367c60f915a262638bb138f55e71442c9df432/src/pointers.jl#L56

which would be great to see in the docs.

**Comment by fleimgruber** [comment]
Anyways, solved for me.
