### ISSUE TITLE
Raw Binary Access

### ISSUE THREAD

**Issue by g7uvw** [analytech-solutions/CBinding.jl#91]
Hello,
I've got the basics of raw binary access working using CBinding to treat the first 512 bytes of a binary file as a C++ struct, I can read the file and display the content of the struct at read-time. My issue is accessing elements of the struct afterwards. 
This is the code I have so far.
```
`using CBinding

#create compiler context
c``

c"#include <stdint.h>"s
const c"uint8_t" = UInt8
const c"int32_t" = Int32
const c"uint16_t" = UInt16
const c"uint32_t" = UInt32

c"""
struct TOMHEAD
    {
        uint16_t xsize,ysize,zsize,lmarg,rmarg,tmarg,bmarg,tzmarg,bzmarg,\
        num_samples,num_proj,num_blocks,num_slices,bin,gain,speed,pepper,calibrationissue,num_frames,machine,spare_int[12];
        float scale,offset,voltage,current,thickness,pixel_size,distance,exposure,\
        mag_factor,filterb,correction_factor,spare_float[2];
        uint32_t z_shift,z,theta ;
        char time[26],duration[12],owner[21],user[5],specimen[32],scan[32],\
        comment[64],spare_char[192];
    };
    """j
header = open("ds_aye-aye1.tom") do io
    display(read(io, TOMHEAD))
end;

volsize = header.xsize * header.ysize * header.zsize`
```
At runtime this outputs:
```
var"(c\"struct TOMHEAD\")" (512-byte struct)
  xsize             = 0x0480
  ysize             = 0x0124
  zsize             = 0x0672
...
[rest of header removed for simplicity]
...
ERROR: LoadError: type Nothing has no field xsize
Stacktrace:
 [1] getproperty(x::Nothing, f::Symbol)
   @ Base ./Base.jl:42
 [2] top-level scope
   @ ~/Development/julia/tom/tom.jl:31
in expression starting at ~/Development/julia/tom/tom.jl:31
```
What's the correct syntax to get at values from the header I've just loaded? The original example code at [analytech-solutions](http://www.analytech-solutions.com/analytech-solutions/blog/binary-io.html) makes me think I'm doing the right thing, but I'm not sure.

**Comment by krrutkow** [comment]
```
header = open("ds_aye-aye1.tom") do io
    display(read(io, TOMHEAD))
end;
```
`display(...)` is returning `nothing`, and that then gets assigned to `header`.  Perhaps try this:
```
header = open("ds_aye-aye1.tom") do io
    read(io, TOMHEAD)
end;
display(header)
# ...
```

**Comment by g7uvw** [comment]
> ```
> header = open("ds_aye-aye1.tom") do io
>     display(read(io, TOMHEAD))
> end;
> ```
> 
> `display(...)` is returning `nothing`, and that then gets assigned to `header`. Perhaps try this:
> 
> ```
> header = open("ds_aye-aye1.tom") do io
>     read(io, TOMHEAD)
> end;
> display(header)
> # ...
> ```

Perfect - thank you!
